-- Fuel module core tables: tanks, log, deliveries, dipstick, issuance

CREATE TABLE IF NOT EXISTS fuel_tanks (
  id               text        PRIMARY KEY,
  tank_code        text,
  name             text        NOT NULL,
  fuel_type        text        DEFAULT 'DIESEL',
  capacity         numeric     NOT NULL,
  current_level    numeric     DEFAULT 0,
  location         text,
  tank_type        text        DEFAULT 'above_ground',
  station_name     text,
  is_bowser        boolean     DEFAULT false,
  is_active        boolean     DEFAULT true,
  unit_cost        numeric     DEFAULT 0,
  alert_threshold  numeric     DEFAULT 200,
  gl_account_code  text,
  expense_account  text,
  gl_asset_account    text,
  gl_expense_account  text,
  attendant_name   text,
  last_dip_date    date,
  last_dip_value   numeric     DEFAULT 0,
  notes            text,
  created_at       timestamptz DEFAULT now(),
  updated_at       timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS fuel_log (
  id            text    PRIMARY KEY,
  date          text,
  time          text,
  fuel_type     text,
  amount        numeric,
  vehicle       text,
  driver        text,
  authorized_by text,
  purpose       text,
  odometer      text,
  dip_before    text,
  dip_after     text,
  user_name     text,
  flowmeter     numeric DEFAULT 0,
  txn_code      text,
  created_at    timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS fuel_deliveries (
  id                 text    PRIMARY KEY,
  date               text,
  fuel_type          text,
  qty                numeric,
  supplier           text,
  delivery_note      text,
  dip_before         text,
  dip_after          text,
  amount             numeric DEFAULT 0,
  gl_asset_account   text,
  gl_payable_account text,
  gl_posted          boolean DEFAULT false,
  notes              text,
  user_name          text,
  created_at         timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dipstick_log (
  id               text    PRIMARY KEY,
  tank_id          text    REFERENCES fuel_tanks(id),
  date             text,
  dip_start        numeric,
  dip_end          numeric,
  fuel_start       numeric,
  fuel_end         numeric,
  fm_start         numeric DEFAULT 0,
  fm_end           numeric DEFAULT 0,
  flowmeter_issued numeric DEFAULT 0,
  actual_issued    numeric DEFAULT 0,
  error_liters     numeric DEFAULT 0,
  error_pct        numeric DEFAULT 0,
  done_by          text,
  user_name        text,
  notes            text,
  created_at       timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS fuel_issuance (
  id               text    PRIMARY KEY,
  tank_id          text    REFERENCES fuel_tanks(id),
  date             date    NOT NULL,
  time             time,
  fuel_type        text    DEFAULT 'DIESEL',
  quantity         numeric NOT NULL,
  amount           numeric,
  equipment_type   text    NOT NULL,
  equipment_id     text,
  equipment_name   text,
  driver_operator  text,
  odometer_reading numeric,
  engine_hours     numeric,
  meter_reading    numeric,
  authorized_by    text,
  purpose          text,
  notes            text,
  txn_code         text,
  unit_cost        numeric DEFAULT 0,
  total_cost       numeric DEFAULT 0,
  project_id       text,
  cost_center      text,
  approval_status  text    DEFAULT 'approved',
  approved_by      text,
  rejection_reason text,
  shift_id         text,
  fuel_request_id  text,
  asset_id         text,
  gl_entry_id      text,
  gl_posted        boolean DEFAULT false,
  date_text        text,
  created_by       text,
  created_at       timestamptz DEFAULT now()
);
