// src/components/ui/index.js — barrel export for shared UI primitives
export { StatusBadge }           from './StatusBadge'
export { ModalDialog, ModalActions } from './ModalDialog'
export { ConfirmDialog }         from './ConfirmDialog'
export { PageHeader }            from './PageHeader'
export { KPICard }               from './KPICard'
export { EmptyState }            from './EmptyState'
export { SectionCard }           from './SectionCard'
export { TabNav }                from './TabNav'
export { AlertBanner }           from './AlertBanner'
export { DataTable }              from './DataTable'
export { Spinner }                from './Spinner'
export { StatBar, SegmentedBar }  from './StatBar'
export { ChartCard }              from './ChartCard'
export { Pagination }             from './Pagination'
export { default as RichTextEditor, stripHtml, isHtmlContent } from './RichTextEditor'
